/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.brutus.view;

import br.com.brutus.bean.Cliente;
import br.com.brutus.bean.Endereco;
import br.com.brutus.bean.Pedido;
import br.com.brutus.bean.PedidoProduto;
import br.com.brutus.bean.Produto;
import br.com.brutus.dao.ClienteDaoImpl;
import br.com.brutus.dao.EnderecoDaoImpl;
import br.com.brutus.dao.PedidoDaoImpl;
import br.com.brutus.dao.PedidoProdutoDaoImpl;
import br.com.brutus.dao.ProdutoDaoImpl;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.senac.dao.ConnectionFactory;

/**
 *
 * @author thiag
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    private DefaultTableModel tableModelCliente;
    private DefaultTableModel tableModelProduto;
    private DefaultTableModel tableModelPedido;
    private EntityManager entityManager;
    private ClienteDaoImpl clienteDao;
    private EnderecoDaoImpl enderecoDao;
    private PedidoDaoImpl pedidoDao;
    private ProdutoDaoImpl produtoDao;
    private PedidoProdutoDaoImpl pedProdDao;

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        this.setTitle("BRUTTUS GRILL");
        this.tableModelCliente = (DefaultTableModel) this.tableClientes.getModel();
        this.tableModelProduto = (DefaultTableModel) this.tableProdutos.getModel();
        this.tableModelPedido = (DefaultTableModel) this.tablePedidos.getModel();
        this.entityManager = new ConnectionFactory().openConnection("BrutusGrillPU");
        this.clienteDao = new ClienteDaoImpl(entityManager);
        this.enderecoDao = new EnderecoDaoImpl(entityManager);
        this.pedidoDao = new PedidoDaoImpl(entityManager);
        this.produtoDao = new ProdutoDaoImpl(entityManager);
        this.pedProdDao = new PedidoProdutoDaoImpl(entityManager);
        preencherTabelaCliente();
        preencherTabelaProduto();
        preencherTabelaPedido();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        logoBrutusGrill = new javax.swing.JLabel();
        cxGuias = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePedidos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable();
        painelFaturamento = new javax.swing.JPanel();
        labelFaturamento = new javax.swing.JLabel();
        labelTotalPedidos = new javax.swing.JLabel();
        labelTotalProdutos = new javax.swing.JLabel();
        labelTotalClientes = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelResultadoPedidos = new javax.swing.JLabel();
        labelResultadoProdutos = new javax.swing.JLabel();
        labelResultadoClientes = new javax.swing.JLabel();
        labelResultadoVendas = new javax.swing.JLabel();
        btAtualizarResumo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logoWhats = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btMenuArquivo = new javax.swing.JMenu();
        btMenuSair = new javax.swing.JMenuItem();
        btMenuCliente = new javax.swing.JMenu();
        btMenuNovoCliente = new javax.swing.JMenuItem();
        btMenuExcluirCliente = new javax.swing.JMenuItem();
        btMenuProdutos = new javax.swing.JMenu();
        btMenuProduto = new javax.swing.JMenuItem();
        btMenuExcluirProduto = new javax.swing.JMenuItem();
        btMenuPedidos = new javax.swing.JMenu();
        brMenuNovoPedido = new javax.swing.JMenuItem();
        brMenuExcluirPedido = new javax.swing.JMenuItem();
        btMenuDetalhes = new javax.swing.JMenuItem();
        btMenuAjuda = new javax.swing.JMenu();
        btMenuSobre = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        logoBrutusGrill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/brutus/icons/brutusgrill.png"))); // NOI18N

        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Telefone", "Email", "Rua", "Número", "Bairro", "Cidade", "UF", "País"
            }
        ));
        jScrollPane1.setViewportView(tableClientes);

        cxGuias.addTab("Clientes", jScrollPane1);

        tablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número Pedido", "Cliente", "Valor Total (R$)", "Data Pedido", "Forma de Pagamento"
            }
        ));
        jScrollPane3.setViewportView(tablePedidos);

        cxGuias.addTab("Pedidos", jScrollPane3);

        tableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Preço por Kg (R$)"
            }
        ));
        jScrollPane2.setViewportView(tableProdutos);

        cxGuias.addTab("Produtos", jScrollPane2);

        painelFaturamento.setBackground(new java.awt.Color(255, 255, 255));

        labelFaturamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelFaturamento.setText("RESUMO");

        labelTotalPedidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTotalPedidos.setText("Total de pedidos:");

        labelTotalProdutos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTotalProdutos.setText("Total de produtos:");

        labelTotalClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTotalClientes.setText("Total de clientes:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Total de vendas:");

        labelResultadoPedidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelResultadoPedidos.setForeground(new java.awt.Color(255, 0, 0));

        labelResultadoProdutos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelResultadoProdutos.setForeground(new java.awt.Color(255, 0, 0));

        labelResultadoClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelResultadoClientes.setForeground(new java.awt.Color(255, 0, 0));

        labelResultadoVendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelResultadoVendas.setForeground(new java.awt.Color(255, 0, 0));

        btAtualizarResumo.setText("Atualizar");
        btAtualizarResumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarResumoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelFaturamentoLayout = new javax.swing.GroupLayout(painelFaturamento);
        painelFaturamento.setLayout(painelFaturamentoLayout);
        painelFaturamentoLayout.setHorizontalGroup(
            painelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFaturamentoLayout.createSequentialGroup()
                .addGroup(painelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFaturamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFaturamento)
                            .addGroup(painelFaturamentoLayout.createSequentialGroup()
                                .addComponent(labelTotalPedidos)
                                .addGap(18, 18, 18)
                                .addComponent(labelResultadoPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelFaturamentoLayout.createSequentialGroup()
                                .addComponent(labelTotalProdutos)
                                .addGap(18, 18, 18)
                                .addComponent(labelResultadoProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelFaturamentoLayout.createSequentialGroup()
                                .addComponent(labelTotalClientes)
                                .addGap(18, 18, 18)
                                .addComponent(labelResultadoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelFaturamentoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(labelResultadoVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(painelFaturamentoLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btAtualizarResumo)))
                .addContainerGap(1090, Short.MAX_VALUE))
        );
        painelFaturamentoLayout.setVerticalGroup(
            painelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFaturamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFaturamento)
                .addGap(38, 38, 38)
                .addGroup(painelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalPedidos)
                    .addComponent(labelResultadoPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelTotalProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelResultadoProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalClientes)
                    .addComponent(labelResultadoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(painelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelResultadoVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btAtualizarResumo)
                .addGap(415, 415, 415))
        );

        cxGuias.addTab("Faturamento", painelFaturamento);

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("CHURRASCO NA BRASA");

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Telefone:(48)9 9602-8882");

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("Rua Verde Vale,119 - Picadas do Sul");

        logoWhats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/brutus/icons/whats.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(logoBrutusGrill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoWhats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)))
                .addContainerGap())
            .addComponent(cxGuias)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoBrutusGrill, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoWhats)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cxGuias)
                .addContainerGap())
        );

        btMenuArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/brutus/icons/folder.png"))); // NOI18N
        btMenuArquivo.setText("Arquivo");

        btMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/brutus/icons/status_offline.png"))); // NOI18N
        btMenuSair.setText("Sair");
        btMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuSairActionPerformed(evt);
            }
        });
        btMenuArquivo.add(btMenuSair);

        jMenuBar1.add(btMenuArquivo);

        btMenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/brutus/icons/usuario.png"))); // NOI18N
        btMenuCliente.setText("Cliente");

        btMenuNovoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/brutus/icons/novoCliente.png"))); // NOI18N
        btMenuNovoCliente.setText("Novo Cliente");
        btMenuNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuNovoClienteActionPerformed(evt);
            }
        });
        btMenuCliente.add(btMenuNovoCliente);

        btMenuExcluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/brutus/icons/deleteCliente.png"))); // NOI18N
        btMenuExcluirCliente.setText("Excluir Cliente");
        btMenuExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuExcluirClienteActionPerformed(evt);
            }
        });
        btMenuCliente.add(btMenuExcluirCliente);

        jMenuBar1.add(btMenuCliente);

        btMenuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/brutus/icons/status_na.png"))); // NOI18N
        btMenuProdutos.setText("Produtos");

        btMenuProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/brutus/icons/plus.png"))); // NOI18N
        btMenuProduto.setText("Novo Produto");
        btMenuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuProdutoActionPerformed(evt);
            }
        });
        btMenuProdutos.add(btMenuProduto);

        btMenuExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/brutus/icons/xVermelho.png"))); // NOI18N
        btMenuExcluirProduto.setText("Excluir Produto");
        btMenuExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuExcluirProdutoActionPerformed(evt);
            }
        });
        btMenuProdutos.add(btMenuExcluirProduto);

        jMenuBar1.add(btMenuProdutos);

        btMenuPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/brutus/icons/time.png"))); // NOI18N
        btMenuPedidos.setText("Pedidos");

        brMenuNovoPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/brutus/icons/add.png"))); // NOI18N
        brMenuNovoPedido.setText("Novo Pedido");
        brMenuNovoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brMenuNovoPedidoActionPerformed(evt);
            }
        });
        btMenuPedidos.add(brMenuNovoPedido);

        brMenuExcluirPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/brutus/icons/xVermelho.png"))); // NOI18N
        brMenuExcluirPedido.setText("Excluir Pedido");
        brMenuExcluirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brMenuExcluirPedidoActionPerformed(evt);
            }
        });
        btMenuPedidos.add(brMenuExcluirPedido);

        btMenuDetalhes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/brutus/icons/time.png"))); // NOI18N
        btMenuDetalhes.setText("Detalhes Pedido");
        btMenuDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuDetalhesActionPerformed(evt);
            }
        });
        btMenuPedidos.add(btMenuDetalhes);

        jMenuBar1.add(btMenuPedidos);

        btMenuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/brutus/icons/status_online.png"))); // NOI18N
        btMenuAjuda.setText("Ajuda");

        btMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/brutus/icons/java.png"))); // NOI18N
        btMenuSobre.setText("Sobre");
        btMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuSobreActionPerformed(evt);
            }
        });
        btMenuAjuda.add(btMenuSobre);

        jMenuBar1.add(btMenuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuSobreActionPerformed
        JanelaDeveloper jdl = new JanelaDeveloper();
        jdl.setVisible(true);
    }//GEN-LAST:event_btMenuSobreActionPerformed

    private void btMenuNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuNovoClienteActionPerformed

        JanelaNovoCliente jnc = new JanelaNovoCliente(this.entityManager,
                this.clienteDao, this.enderecoDao, this.tableModelCliente);
        jnc.setVisible(true);

    }//GEN-LAST:event_btMenuNovoClienteActionPerformed

    private void btMenuExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuExcluirClienteActionPerformed

        int[] linhasSelecionadas = this.tableClientes.getSelectedRows();

        for (int i = 0; i < linhasSelecionadas.length; i++) {

            int id = (int) this.tableModelCliente.getValueAt(linhasSelecionadas[i], 0);

            Cliente cliente = (Cliente) this.clienteDao.searchById(Cliente.class, id);
            Endereco endereco = (Endereco) this.enderecoDao.searchById(Endereco.class, cliente.getEndereco().getId());

            this.clienteDao.delete(cliente);
            this.enderecoDao.delete(endereco);
            this.tableModelCliente.removeRow(linhasSelecionadas[i]);

            for (int j = i + 1; j < linhasSelecionadas.length; j++) {

                linhasSelecionadas[j] = linhasSelecionadas[j] - 1;
            }
        }

    }//GEN-LAST:event_btMenuExcluirClienteActionPerformed

    private void btMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuSairActionPerformed
        this.entityManager.close();
        System.exit(0);
    }//GEN-LAST:event_btMenuSairActionPerformed

    private void btMenuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuProdutoActionPerformed
        JanelaCadastrarProduto jcp = new JanelaCadastrarProduto(this.produtoDao, this.tableModelProduto);
        jcp.setVisible(true);
    }//GEN-LAST:event_btMenuProdutoActionPerformed

    private void btMenuExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuExcluirProdutoActionPerformed

        int[] linhasSelecionadas = this.tableProdutos.getSelectedRows();

        for (int i = 0; i < linhasSelecionadas.length; i++) {

            int id = (int) this.tableModelProduto.getValueAt(linhasSelecionadas[i], 0);
            Produto produto = (Produto) this.produtoDao.searchById(Produto.class, id);

            this.produtoDao.delete(produto);
            this.tableModelProduto.removeRow(linhasSelecionadas[i]);

            for (int j = i + 1; j < linhasSelecionadas.length; j++) {

                linhasSelecionadas[j] = linhasSelecionadas[j] - 1;
            }
        }

    }//GEN-LAST:event_btMenuExcluirProdutoActionPerformed

    private void brMenuExcluirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brMenuExcluirPedidoActionPerformed

        int[] linhasSelecionadas = this.tablePedidos.getSelectedRows();

        for (int i = 0; i < linhasSelecionadas.length; i++) {

            int id = (int) this.tableModelPedido.getValueAt(linhasSelecionadas[i], 0);
            Pedido pedido = (Pedido) this.pedidoDao.searchById(Pedido.class, id);
            List<PedidoProduto> listaPP = this.pedProdDao.procurarPorIdPedido(pedido.getId());
            
            for (int j = 0; j < listaPP.size(); j++) {
                if (listaPP.get(j).getPedido().getId() == pedido.getId()) {
                    this.pedProdDao.delete(listaPP.get(j));
                }
            }
            this.pedidoDao.delete(pedido);
            this.tableModelPedido.removeRow(linhasSelecionadas[i]);

            for (int j = i + 1; j < linhasSelecionadas.length; j++) {

                linhasSelecionadas[j] = linhasSelecionadas[j] - 1;
            }
        }

    }//GEN-LAST:event_brMenuExcluirPedidoActionPerformed

    private void brMenuNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brMenuNovoPedidoActionPerformed

        JanelaNovoPedido jnp = new JanelaNovoPedido(this.entityManager, this.clienteDao, this.enderecoDao, this.tableModelCliente, this.produtoDao, this.tableModelPedido);
        jnp.setVisible(true);
    }//GEN-LAST:event_brMenuNovoPedidoActionPerformed

    private void btAtualizarResumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarResumoActionPerformed

        preencherResumo();

    }//GEN-LAST:event_btAtualizarResumoActionPerformed

    private void btMenuDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuDetalhesActionPerformed

        int id = 0;

        int[] linhasSelecionadas = this.tablePedidos.getSelectedRows();

        for (int i = 0; i < linhasSelecionadas.length; i++) {

            id = (int) this.tableModelPedido.getValueAt(linhasSelecionadas[i], 0);

            for (int j = i + 1; j < linhasSelecionadas.length; j++) {

                linhasSelecionadas[j] = linhasSelecionadas[j] - 1;
            }
        }
        if (id != 0) {
            JanelaDetalhesPedido jdp = new JanelaDetalhesPedido(entityManager, clienteDao, produtoDao, id, pedidoDao);
            jdp.setVisible(true);
        }
    }//GEN-LAST:event_btMenuDetalhesActionPerformed

    /**
     * @param args the command line arguments
     */
    private void preencherTabelaCliente() {

        List<Cliente> lista = clienteDao.pesquisarTodosClientes();
        for (int i = 0; i < lista.size(); i++) {
            Cliente cliente = lista.get(i);
            Endereco endereco = (Endereco) this.enderecoDao.searchById(Endereco.class, cliente.getEndereco().getId());

            this.tableModelCliente.addRow(new Object[]{cliente.getNome(),
                cliente.getCpf(), cliente.getTelefone(), cliente.getEmail(),
                endereco.getRua(), endereco.getNumero(), endereco.getBairro(),
                endereco.getCidade(), endereco.getUf(), endereco.getPais()});
        }
    }

    private void preencherTabelaProduto() {

        List<Produto> produtos = produtoDao.pesquisarTodosProdutos();
        for (int i = 0; i < produtos.size(); i++) {
            Produto produto = produtos.get(i);

            this.tableModelProduto.addRow(new Object[]{produto.getId(), produto.getNome(), produto.getValor()});
        }
    }

    private void preencherTabelaPedido() {

        List<Object[]> pedidos = pedidoDao.pesquisarTodosPedidos();

        for (Object[] pedido : pedidos) {
            Pedido pc2 = (Pedido) pedido[0];
            Cliente c = (Cliente) pedido[1];

            SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");

            this.tableModelPedido.addRow(new Object[]{pc2.getId(), c.getNome(),
                pc2.getValorTotal(), formatador.format(pc2.getDtPedido()), pc2.getFormaPagamento()});
        }
    }

    private void preencherResumo() {
        List<Cliente> clientes = clienteDao.pesquisarTodosClientes();
        List<Produto> produtos = produtoDao.pesquisarTodosProdutos();
        List<Object[]> pedidos = pedidoDao.pesquisarTodosPedidos();

        Integer qtdPedidos = pedidos.size();
        this.labelResultadoPedidos.setText(qtdPedidos.toString());
        Integer qtdClientes = clientes.size();
        this.labelResultadoClientes.setText(qtdClientes.toString());
        Integer qtdProdutos = produtos.size();
        this.labelResultadoProdutos.setText(qtdProdutos.toString());

        Double resultado = 0.0;
        for (Object[] pedido : pedidos) {
            Pedido p = (Pedido) pedido[0];
            resultado += p.getValorTotal();
        }
        this.labelResultadoVendas.setText("R$ " + resultado.toString());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem brMenuExcluirPedido;
    private javax.swing.JMenuItem brMenuNovoPedido;
    private javax.swing.JButton btAtualizarResumo;
    private javax.swing.JMenu btMenuAjuda;
    private javax.swing.JMenu btMenuArquivo;
    private javax.swing.JMenu btMenuCliente;
    private javax.swing.JMenuItem btMenuDetalhes;
    private javax.swing.JMenuItem btMenuExcluirCliente;
    private javax.swing.JMenuItem btMenuExcluirProduto;
    private javax.swing.JMenuItem btMenuNovoCliente;
    private javax.swing.JMenu btMenuPedidos;
    private javax.swing.JMenuItem btMenuProduto;
    private javax.swing.JMenu btMenuProdutos;
    private javax.swing.JMenuItem btMenuSair;
    private javax.swing.JMenuItem btMenuSobre;
    private javax.swing.JTabbedPane cxGuias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelFaturamento;
    private javax.swing.JLabel labelResultadoClientes;
    private javax.swing.JLabel labelResultadoPedidos;
    private javax.swing.JLabel labelResultadoProdutos;
    private javax.swing.JLabel labelResultadoVendas;
    private javax.swing.JLabel labelTotalClientes;
    private javax.swing.JLabel labelTotalPedidos;
    private javax.swing.JLabel labelTotalProdutos;
    private javax.swing.JLabel logoBrutusGrill;
    private javax.swing.JLabel logoWhats;
    private javax.swing.JPanel painelFaturamento;
    private javax.swing.JTable tableClientes;
    private javax.swing.JTable tablePedidos;
    private javax.swing.JTable tableProdutos;
    // End of variables declaration//GEN-END:variables
}
