/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.brutus.view;

import br.com.brutus.bean.Cliente;
import br.com.brutus.bean.Pedido;
import br.com.brutus.bean.PedidoProduto;
import br.com.brutus.bean.Produto;
import br.com.brutus.dao.ClienteDaoImpl;
import br.com.brutus.dao.PedidoDaoImpl;
import br.com.brutus.dao.PedidoProdutoDaoImpl;
import br.com.brutus.dao.ProdutoDaoImpl;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author thiag
 */
public class JanelaDetalhesPedido extends javax.swing.JFrame {

    private EntityManager entityManager;
    private ClienteDaoImpl clienteDao;
    private ProdutoDaoImpl produtoDao;
    private PedidoProdutoDaoImpl pedidoProdDao;
    private PedidoDaoImpl pedidoDao;
    private DefaultTableModel tableDetalhes;
    private int id;

    /**
     * Creates new form JanelaDetalhesPedido
     */
    public JanelaDetalhesPedido() {
        initComponents();
    }

    public JanelaDetalhesPedido(EntityManager em, ClienteDaoImpl cdi, ProdutoDaoImpl pdi, int id, PedidoDaoImpl peddi) {
        initComponents();
        this.setTitle("Detalhes do pedido");
        this.entityManager = em;
        this.clienteDao = cdi;
        this.produtoDao = pdi;
        this.pedidoDao = peddi;
        this.pedidoProdDao = new PedidoProdutoDaoImpl(this.entityManager);
        this.tableDetalhes = (DefaultTableModel) this.tableDetalhesPedido.getModel();
        this.id = id;
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDetalhesPedido = new javax.swing.JTable();
        labelDetalhesPedido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tableDetalhesPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pedido", "Cliente", "Produto", "Peso", "Valor"
            }
        ));
        jScrollPane1.setViewportView(tableDetalhesPedido);

        labelDetalhesPedido.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelDetalhesPedido.setText("Detalhes do pedido:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDetalhesPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDetalhesPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void preencherTabela() {
        Pedido pedido = (Pedido) this.pedidoDao.searchById(Pedido.class, this.id);
        List<PedidoProduto> listaPP = this.pedidoProdDao.procurarPorIdPedido(this.id);
        Cliente cliente = (Cliente) this.clienteDao.searchById(Cliente.class, pedido.getCliente().getId());

        for (int i = 0; i < listaPP.size(); i++) {
            if (listaPP.get(i).getPedido().getId() == this.id) {
                Produto produto = (Produto) this.produtoDao.searchById(Produto.class, listaPP.get(i).getProduto().getId());
                this.tableDetalhes.addRow(new Object[]{pedido.getId(),
                    cliente.getNome(), produto.getNome(),
                    listaPP.get(i).getPeso(), listaPP.get(i).getValor()});
            }
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDetalhesPedido;
    private javax.swing.JTable tableDetalhesPedido;
    // End of variables declaration//GEN-END:variables
}
